### ISSUE TITLE
unexpected argument ‘extraLibs’ in CheckMATE

### ISSUE THREAD

**Issue by cbpark** [wavewave/hep-nix-overlay#20]
When I attempted to build `CheckMATE`, I got the error message as follows.

error: anonymous function at "/nix/store/0g2b345qz577nxx69wi1rnxv5zjindrw-nixpkgs-15.05pre57176.b9cc043/nixpkgs/pkgs/development/interpreters/python/2.7/default.nix":1:1 called with unexpected argument ‘extraLibs’, at "/nix/store/0g2b345qz577nxx69wi1rnxv5zjindrw-nixpkgs-15.05pre57176.b9cc043/nixpkgs/lib/customisation.nix":58:12

It seems that it is claiming about the lines of

```nix
  pythonCheckMATE = pkgs.pythonFull.override { 
                      extraLibs = with pkgs.pythonPackages; [ numpy ];
                    };
```

in `pkgs/CheckMATE/default.nix`. So, I removed the lines and modified `buildInputs` like

```nix
buildInputs = [ root5 pkgs.which pkgs.tcl python pythonPackages.numpy ];
```

and then, modified `buildInputs` in `pkgs/CheckMATE/env.nix` in the similar way. After all, I found that the build was successful. If you wish to see it, I will send a pull request.

**Comment by wavewave** [comment]
Thanks. It seems that python policy has been changed.

How about runtime behavior? In any case, please send me the pull request.

best,
IW

**Comment by cbpark** [comment]
I have sent the pull request. See [here](https://github.com/wavewave/hep-nix-overlay/pull/21).
